{
    'name': 'Odoo School Coworking Management',
    'summary': 'Manage coworking locations, resources, bookings, memberships, and visits.',
    'author': 'Odoo School Student',
    'website': 'https://odoo.school/',
    'category': 'Customizations',
    'version': '19.0.1.0.0',
    'license': 'OPL-1',
    'depends': [
        'base',
        'mail',
        'product',
        'calendar',
        'web',
    ],
    'data': [
        'security/os_coworking_groups.xml',
        'security/os_coworking_security.xml',
        'security/ir.model.access.csv',
        'data/os_coworking_sequences.xml',
        'views/os_coworking_menu_views.xml',
        'views/os_coworking_location_views.xml',
        'views/os_coworking_resource_views.xml',
    ],
    'demo': [
        'demo/os_coworking_location_demo.xml',
        'demo/os_coworking_resource_demo.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
