{
    'name': 'Odoo School Coworking Management',
    'summary': 'Manage coworking locations, resources, bookings, memberships, and visits.',
    'author': 'Odoo School Student',
    'website': 'https://odoo.school/',
    'category': 'Customizations',
    'version': '19.0.1.0.0',
    'license': 'OPL-1',
    'depends': [
        'base',
        'mail',
        'product',
        'web',
    ],
    'data': [
        'security/os_coworking_groups.xml',
        'security/os_coworking_security.xml',
        'security/ir.model.access.csv',
        'data/os_coworking_sequences.xml',
        'data/os_coworking_membership_cron.xml',
        'views/os_coworking_menu_views.xml',
        'views/os_coworking_location_views.xml',
        'views/os_coworking_resource_views.xml',
        'views/os_coworking_membership_plan_views.xml',
        'views/os_coworking_membership_views.xml',
        'views/os_coworking_booking_views.xml',
        'views/os_coworking_visit_views.xml',
        'wizard/os_coworking_availability_wizard_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'report/os_coworking_booking_report.xml',
        'report/os_coworking_membership_invoice_report.xml',
    ],
    'demo': [
        'demo/os_coworking_user_demo.xml',
        'demo/os_coworking_partner_demo.xml',
        'demo/os_coworking_location_demo.xml',
        'demo/os_coworking_resource_demo.xml',
        'demo/os_coworking_membership_plan_demo.xml',
        'demo/os_coworking_product_demo.xml',
        'demo/os_coworking_membership_demo.xml',
        'demo/os_coworking_booking_demo.xml',
        'demo/os_coworking_visit_demo.xml',
    ],
    'images': [
        'static/description/banner.png',
        'static/description/icon.png',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
